{% set name = "neo4j" %}
{% set version = "5.14.1" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neo4j-{{ version }}.tar.gz
  sha256: 3200be8550ed16622b2fadf4f749d08b9982989c4bfce6f99ab693f104104cb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools >=66.1.0
    - tomlkit >=0.11.6,<0.12.dev0
    - pip
  run:
    - python >=3.7
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  summary: Neo4j Bolt driver for Python
  license: Apache-2.0 AND Python-2.0 AND MulanPSL-2.0
  license_file:
    - LICENSE.APACHE2.txt
    - LICENSE.PYTHON.txt
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
