{% set version = "4.0.0" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: c65c60c587da02da30080d34c66118482aa208c7c610ec0ca9b7f243ea74dde8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - neotime >=1.7.1,<1.8.0
    - neobolt >=1.7.15,<1.8.0

test:
  imports:
    - neo4j
    - neo4j.compat
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
