{% set version = "1.6.2" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: 2d459cb3ff7fefe74e679d239bae7ee19fd83b8131ebd8c90b4cf86d9b394b63

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - neotime

test:
  imports:
    - neo4j
    - neo4j.bolt
    - neo4j.compat
    - neo4j.packstream
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
