{% set version = "1.7.3" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: a144c93b3976bf439e81ce386dfcee3028e6d2e0baca61e62942a00159d79c40

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - neotime <2,>=1.7.1
    - neobolt <2,>=1.7.4

test:
  imports:
    - neo4j
    - neo4j.compat
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
