{% set name='neo4j-python-driver' %}
{% set version='1.5.0' %}
{% set sha256='a5eab2123df734896912bbdececefd3ae4e3fe2c0e72e87136ba2776d03ed0b8' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/neo4j/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - toolchain
    - python
    - cython
    - setuptools
  run:
    - python

test:
  imports:
    - neo4j
    - neo4j.bolt
    - neo4j.compat
    - neo4j.packstream
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
