{% set name = "neo4j" %}
{% set version = "5.26.0" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neo4j-{{ version }}.tar.gz
  sha256: 51b25ba127b7b9fdae1ddf48ae697ddfab331e60f4b6d8488d1fc1f74ec60dcc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - tomlkit ==0.11.8
    - pip
  run:
    - python >=3.7
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  summary: Neo4j Bolt driver for Python
  license: Apache-2.0 AND Python-2.0 AND MulanPSL-2.0
  license_file:
    - LICENSE.APACHE2.txt
    - LICENSE.PYTHON.txt
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
