{% set version = "5.6.0" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/neo4j/neo4j-{{ version }}.tar.gz
  sha256: 99ba8321195a114a870704dd00463a0429c364c97dde603b39841e78ac05b97c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=65.6,<66.0
    - tomlkit >=0.11.6,<1.0.0
  run:
    - python >=3.7
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Neo4j Bolt driver for Python

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
