{% set name = "neo4j" %}
{% set version = "5.9.0" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neo4j-{{ version }}.tar.gz
  sha256: b0abc0065f616bfd8230a48b1f6c91f9aacd7e2aea76d72d09a745ae169cf4da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=65.6,<66.0
    - tomlkit >=0.11.6,<1.0.0
  run:
    - python >=3.7
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  summary: Neo4j Bolt driver for Python
  license: Apache-2.0 AND Python-2.0 AND MulanPSL-2.0
  license_file:
    - LICENSE.APACHE2.txt
    - LICENSE.PYTHON.txt
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
