{% set version = "4.3.2" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/neo4j/neo4j-{{ version }}.tar.gz
  sha256: 74b28ec5cedc79b5bfa55ab3ed7da5edd02846f0e836dff7cd14bbf698774e3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
