{% set name = "neo4j-python-drive" %}
{% set version = "5.3.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/neo4j/neo4j-{{ version }}.tar.gz
  sha256: 0c1c7d8812eed60da0a442d1e0f35edbda248255703e506a081cb70e083b3b5c

build:
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.7

outputs:
  - name: {{ name }}
    script: install_neo4j.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools >=65.6,<66.0
        - tomlkit >=0.11.6,<1.0.0
      run:
        - python >=3.7
        - pytz

    test:
      imports:
        - neo4j
        - neo4j.graph
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-pandas
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python  >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - pandas >=1.0.0
    test:
      imports:
        - neo4j
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
