{% set name = "neo4j" %}
{% set version = "5.28.2" %}
{% set python_min = python_min|default("3.7") %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neo4j-{{ version }}.tar.gz
  sha256: 7d38e27e4f987a45cc9052500c6ee27325cb23dae6509037fe31dd7ddaed70c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==75.6.0
    - tomlkit ==0.12.5
    - pip
    # required but not listed upstream
    - wheel
  run:
    - python >={{ python_min }}
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  summary: Neo4j Bolt driver for Python
  license: Apache-2.0 AND Python-2.0
  license_file:
    - LICENSE.APACHE2.txt
    - LICENSE.PYTHON.txt
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
