{% set version = "1.7.2" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: a4ef4d46564f7bef3ffb2da154748c1af5fbb2eafc769616c9bc933738a8115e

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - neotime<2
    - neobolt<2

test:
  imports:
    - neo4j
    - neo4j.compat
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
