{% set name = "neo4j" %}
{% set version = "6.0.0" %}
{% set python_min = python_min|default("3.7") %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neo4j-{{ version }}.tar.gz
  sha256: d49bbf0d5047fbfa495da7fc62e869e728e29bebb01140ec32ac0c1aeb56b9db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==80.9.0
    - pip
  run:
    - python >={{ python_min }}
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  summary: Neo4j Bolt driver for Python
  license: Apache-2.0 AND Python-2.0
  license_file:
    - LICENSE.APACHE2.txt
    - LICENSE.PYTHON.txt
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
