{% set version = "4.4.2" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/neo4j/neo4j-{{ version }}.tar.gz
  sha256: 58f289c4210310740de429d3daef6d6a972c247aeba6820f2fcba4b04bb56204

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
    - xylar
