{% set version = "4.0.2" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: 4d72f868dee124efa8f36af6cf09c97b61725d0c5b5fd0a4def7cb790d7535de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - pytz

test:
  imports:
    - neo4j

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
