{% set version = "4.1.1" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: a754242b8254466fe350e9b482d496d70dff53edbc13ec415e0dff84d9bf8c4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - pytz

test:
  imports:
    - neo4j

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Database connector for Neo4j graph database

extra:
  recipe-maintainers:
    - pvanheus
    - thebestnom
