# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AED8Mgn2MqRWjwio6sqoVymeS0QhMFW5l25hURO+dG++sJ9XLZVZikv+i6lq4MBAKO+LtfZbb97PmSmZk4phF67tKKwr5YxyT79jux/uw4sLmOS8E2B6NWZ4lm2VtdF4HffWsCX0j0CXG0SrntsFUyWkzqRVgg9gX2QCh3EoKMZ3p7Xk25kzjHL2ECp0h6VFmn0Ku3XOyGUm+P39WBGaG8/0dXq6ca/YHrALlNsrGN4H4miQxFVQ2bJ918+0p99eMAYTYCkKM66oJpJL0XOWnEjhGpRdkzLfnb86nlew5PBqpESsESOnKPUKvTHg2wK3xz3sKAglWLN5qMX36Kro9Q9lSI2zbEYOMhVqaRtkhvbDiucpxm3WTHh+2+uE9fghCNoZgtpsERfVzAHHd4LeXinspRRTF2r918czDf0Z2outAhR/Cm+C3qlF7WTBprp6YQA8e1hfUW1uFgKMSUXrv4Xhb2o+4GA0ql/ZBsyf8Y8CeJsGYBxOMKOm1w42jNhfkRcfmvm/NY5sZBa/gzxxyNMQuwr1rhU4rG7boXWQgRoTqQDn/imILjvhF+OiPPlplt0WWkMC19pQ+TNXaUg6dC97ONAr/+XEcrnlyfbK3oOmQvouClu/5Q4xf7XbeTRfFq4xYtKhmjVrJaLFEKbAW29WE7AJ4iE1hFgBODvpG6c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
