appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LDeZM/s+H3Frp61HR9TC3CJIOIFRqbixxklTNmpH35YsjIVdvu4f9EHzLvc0P07K52MvbLvbdYHwbuwhTqWUaGnKjYrXU1+gVSGxq7HiTGNdXBfIJAvvj4xY3NJjlRZPHmEBc6Dz3NLySwf+bRZDVfkPSF7/PWD/QSnASLBoD7PV7UP80A53A6+AX5IdGVZPJ5tb/9FY58NEb8q+HFjlpwkv3TWp7IE6z7AIUfEHp36A6pvCbdiLfwwcQ0/IiMhvq12fWWQ4bbaeDxXKsg2K1RXqWSRpmeeqGk8xUp8hT7h4A97lRoJWFh9oWEBqL5UzKhd84e/lGK+OSADXWrr1BJUdvOgNqciVC3zAi99xrm2aPLJmXKxYbO1flKmfrDp79Y1r+4OSFsi/234KmFXPQCdI89uiOT0GAH8YKeh9fre/lPr9/k/I3SZezeElfm/7PSnmv9CIMeKgi7Rk9ujiZ+6TouYYvcjJF6zZp/ZOxS8Q4uNw4/A7ji4yxrwEoAHGlkZbopWJqaIqOaDoF24uB4bT8t0aEQBdDJ9MrZE+ZU6liAKIZui7LA2xW+VG+IBVOp1yGbCphlVAX8dUXwSkxWAyZqFN9MdMRaSE6ZOlUvTsb0g2LgUBtdpRXWHG5UYWkQXm/oZ0Ptp4Y5P6KNgWM3A/p+uy68Ms8jLzlaoiElI=}
provider:
  win: azure
